language: ruby

before_install:
    - gem install bundler

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE bookmark_manager_test;'

script:
  - bundle exec rake create_tables
  - bundle exec rspec
